### PR TITLE
Update core-graphics to 0.5; update minor version.

### PR DESCRIPTION
**Pull request by jdm**
This change is [Reviewable](https://reviewable.io/reviews/servo/cocoa-rs/150)

### CODE REVIEW

**Comment by tomaka** [comment]
This just broke winit 👎

**Comment by jdm** [comment]
I guess it should have been 0.6 because of exported types?

**Comment by tomaka** [comment]
@jdm Yes

**Comment by jdm** [comment]
Submitted https://github.com/servo/cocoa-rs/pull/151 to bump it to 0.6.0 and yanked 0.5.3. Thanks for letting us know!

**Pull request merged**
