### PR TITLE
Update bitflags and bump version

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/cocoa-rs/163)

### CODE REVIEW

**Comment by Eijebong** [comment]
Do not merge this. I didn't see bitflags 0.9

**Comment by Eijebong** [comment]
Okay, I'm just not sure it compiles and i don't have a mac to test... Kinda hoped travis would help :(

**Comment by jdm** [comment]
Travis compilation will be fixed by #164.

**Comment by Eijebong** [comment]
Cool, waiting for this to land and I'll rebase

**Comment by Eijebong** [comment]
Yay, it now compiles :)

**Comment by jdm** [comment]
This is good to merge when we're ready to upgrade.

**Comment by Eijebong** [comment]
I don't think it'll block anything since it's not a breaking change, right ?

**Pull request merged**
