### PR TITLE
Upgrade to libc 0.2

### PR DESCRIPTION
**Pull request by mbrubeck**
[Review on Reviewable](https://reviewable.io/reviews/servo/cocoa-rs/105)

### CODE REVIEW

**Comment by eefriedman** [comment]
(This has merge conflicts.)

**Comment by metajack** [comment]
Did you make this against the wrong branch?

**Comment by mbrubeck** [comment]
> Did you make this against the wrong branch?

Oops, yes. Fixed. This depends on SSheldon/rust-objc#1 and servo/core-graphics-rs#45.

**Comment by metajack** [comment]
@bors-servo r+


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/servo/cocoa-rs/105)

**Comment by metajack** [comment]
This is blocked on a new objc published to crates.io.

**Comment by SSheldon** [comment]
Version 0.1.8 of objc was published that allows using either libc 0.1 or 0.2 (see SSheldon/rust-objc#30 for discussion). That should unblock this.

**Comment by SSheldon** [comment]
No version 0.2 of objc was published, so this PR will need to be updated to keep using 0.1. (Decided that, since version 0.1 of libc is still allowed with the objc crate, it wasn't a breaking change to justify going to 0.2.)

**Comment by metajack** [comment]
@mbrubeck can you update the version used by cocoa then?

**Pull request merged**
