### PR TITLE
Allow core-graphics 0.8 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**
This change is [Reviewable](https://reviewable.io/reviews/servo/cocoa-rs/162)

### CODE REVIEW

**Comment by nox** [comment]
This may break things downstream for people using core-graphics 0.7. Ranges caused issues in the past already.

**Comment by Eijebong** [comment]
Ok, then let's not do ranges :p

**Comment by killercup** [comment]
@Eijebong asked me to test this, and it compiles fine on macOS 10.12.5 with rustc 1.18 (stable).

**Comment by emilio** [comment]
This still needs an update @Eijebong.

**Comment by Eijebong** [comment]
Woups, pushed on the wrong branch ^^

**Comment by emilio** [comment]
Thanks @killercup for testing again!

**Comment by glennw** [comment]
@bors-servo retry
 * travis?

**Pull request merged**
