### PR TITLE
Add NSDictionary + tests, define NSComparator and NSComparisonResult

### PR DESCRIPTION
**Pull request by burtonageo**
This change is [Reviewable](https://reviewable.io/reviews/servo/cocoa-rs/137)

### CODE REVIEW

**Comment by jdm** [comment]
```
unning 8 tests

test foundation::nsdictionary::test_get ... ok

test foundation::nsdictionary::test_iter ... FAILED

test foundation::nsfastenumeration::test_iter ... ok

test foundation::nsfastenumeration::test_mutation ... ok

test foundation::nsstring::test_append_by_appending_string ... ok

test foundation::nsstring::test_length ... ok

test foundation::nsstring::test_utf8 ... ok

test foundation::nsstring::test_string ... ok

failures:

---- foundation::nsdictionary::test_iter stdout ----

	thread 'foundation::nsdictionary::test_iter' panicked at 'assertion failed: k0.isEqualToString(k1)', tests/foundation.rs:168

note: Run with `RUST_BACKTRACE=1` for a backtrace.

failures:

    foundation::nsdictionary::test_iter

test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured
```

**Comment by burtonageo** [comment]
For some reason this passes locally to me :-/

**Pull request merged**
